name: Build and Deploy FastAPI App to Azure Web App

env:
  AZURE_WEBAPP_NAME: plndapp # Set to your Azure Web App name
  AZURE_CONTAINER_REGISTRY: plndbackend.azurecr.io # Replace with your ACR name
  PYTHON_VERSION: "3.11.10"

on:
  push:
    branches:
      - main # Trigger deployment to production
  pull_request:
    branches:
      - dev # Trigger workflow for testing on dev branch
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv package manager
        run: |
          python -m ensurepip --upgrade  # Ensure Python has ensurepip
          python -m pip install uv  # Install `uv` for managing dependencies
          uv --version  # Verify uv installation

      - name: Sync dependencies with uv
        run: |
          uv sync  # Install dependencies defined in pyproject.toml
          uv status  # Verify that dependencies were installed correctly

      - name: Add pytest and run tests
        run: |
          uv add pytest  # Add pytest as a dev dependency
          uv status  # Check that pytest is added
          pytest tests/  # Run tests (update the path to match your test folder)

      - name: Build Docker image
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/fastapi-app:latest .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/fastapi-app:latest

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/fastapi-app:latest
